spring: 
  cloud:
    gateway:
      routes:
        - id: categoryService
          uri: http://localhost:5820
          predicates:
            - Path=/api/categories/**
        - id: userService
          uri: http://localhost:5821
          predicates:
            - Path=/api/users/**
        - id: otpService
          uri: http://localhost:5822
          predicates:
            - Path=/api/otps/**
        
        
      